regions:
  us:
    base_url: "https://www.youngla.com"
    currency: "USD"
  eu:
    base_url: "https://eu.youngla.com"
    currency: "EUR"
  uk:
    base_url: "https://uk.youngla.com"
    currency: "GBP"

currency_api:
  url: "https://api.exchangerate-api.com/v4/latest/USD"
